name: Monitor CloudFlare IP addresses
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download CloudFlare IP address list
        run: |
          mkdir -p previous
          cp ips-v4 ips-v6 previous/
          curl -o ./ips-v4 https://www.cloudflare.com/ips-v4
          curl -o ./ips-v6 https://www.cloudflare.com/ips-v6

      - name: Check IPv4 list updated
        id: ipv4_list
        run: echo "::set-output name=updated::$(diff previous/ips-v4 ips-v4; echo $?)"

      - name: Check IPv6 list updated
        id: ipv6_list
        run: echo "::set-output name=updated::$(diff previous/ips-v6 ips-v6; echo $?)"

      - name: Generate branch prefix
        if: ${{ steps.ipv4_list.outputs.updated != 0 || steps.ipv6_list.outputs.updated != 0 }}
        id: datetime
        run: |
          echo "::set-output name=now::$(date '+%Y%m%d%H%M')"

      - name: Create Pull Request
        if: ${{ steps.ipv4_list.outputs.updated != 0 || steps.ipv6_list.outputs.updated != 0 }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update new IP address for CloudFlare'
          title: Update new IP address for CloudFlare
          body: |
            @ktanaka26
            - [ ] Review no syntax errors in IP address lists
            - [ ] Update difference to firewall
          branch: update-list-${{ steps.datetime.outputs.now }}
          base: master
          draft: true
